import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class Comparison extends javax.swing.JFrame {

    /**
     * Creates new form Comparison
     */
    public Comparison() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Atomic Number", "Name", "Atomic Weight", "Density", "Melting Point", "Boiling Point", "Electronegativity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 260, 1160, 280);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your choice of comparison", "Atomic Number", "Atomic Weight", "Density", "Melting Point", "Boiling Point", "Electronegativity" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 60, 270, 72);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 90, 180, 44);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter your desired value");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 60, 154, 20);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(343, 236, 154, 22);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a criteria for comparison", "=", "<", ">", "<=", ">=" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(480, 60, 250, 72);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("Click on this button to check result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(740, 60, 270, 72);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setText("Clear all records");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1030, 60, 169, 72);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w0000159.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1230, 570);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(430, 190, 56, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(470, 180, 56, 20);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(430, 190, 59, 20);

        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(470, 200, 59, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel tt=(DefaultTableModel)jTable1.getModel();
    int num;
        String an;
        double am,de,mp,bp,en;
         num=Integer.parseInt(jTextField1.getText());
        try{
                Class.forName("java.sql.DriverManager");
        Connection cc=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/periodic","root","one");
        Statement st=(Statement)cc.createStatement();
        //atomic no
        if(jComboBox1.getSelectedIndex()==1){
            //=
        if(jComboBox2.getSelectedIndex()==1){   
        ResultSet rr=st.executeQuery("select Element_name,Atomic_mass,Density,Melting_point,Boiling_point,Electronegativity from elements where (Atomic_number='"+num+"');");
       while(rr.next()){
                an=rr.getString("Element_name");
                
        am=rr.getDouble("Atomic_mass");
        de=rr.getDouble("Density");
        mp=rr.getDouble("Melting_point");
        bp=rr.getDouble("Boiling_point");
        en=rr.getDouble("Electronegativity");
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);}
        }
                     
         //<
        if(jComboBox2.getSelectedIndex()==2){   
            ResultSet rr=st.executeQuery("select * from elements where Atomic_number<'"+num+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
        //>
            if(jComboBox2.getSelectedIndex()==3){   
            ResultSet rr=st.executeQuery("select * from elements where Atomic_number>'"+num+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
        }
            //<=
        if(jComboBox2.getSelectedIndex()==4){   
            ResultSet rr=st.executeQuery("select * from elements where Atomic_number<='"+num+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
        //>=
        if(jComboBox2.getSelectedIndex()==5){   
            ResultSet rr=st.executeQuery("select * from elements where Atomic_number>='"+num+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
       
        
    }
        }//end of atomic no
        //atomic mass
    am=Double.parseDouble(jTextField1.getText());
   if(jComboBox1.getSelectedIndex()==2){
        if(jComboBox2.getSelectedIndex()==1){   
        ResultSet rr=st.executeQuery("select Element_name,Atomic_mass,Density,Melting_point,Boiling_point,Electronegativity from elements where (Atomic_mass='"+am+"');");
       while(rr.next()){
                an=rr.getString("Element_name");
                
        am=rr.getDouble("Atomic_mass");
        de=rr.getDouble("Density");
        mp=rr.getDouble("Melting_point");
        bp=rr.getDouble("Boiling_point");
        en=rr.getDouble("Electronegativity");
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);}
        }
                     
         
        if(jComboBox2.getSelectedIndex()==2){   
            ResultSet rr=st.executeQuery("select * from elements where Atomic_mass<'"+am+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
            if(jComboBox2.getSelectedIndex()==3){   
            ResultSet rr=st.executeQuery("select * from elements where Atomic_mass>'"+am+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
        }
        if(jComboBox2.getSelectedIndex()==4){   
            ResultSet rr=st.executeQuery("select * from elements where Atomic_mass<='"+am+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
        if(jComboBox2.getSelectedIndex()==5){   
            ResultSet rr=st.executeQuery("select * from elements where Atomic_mass>='"+am+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
       
        }
    }
   de=Double.parseDouble(jTextField1.getText());
       if(jComboBox1.getSelectedIndex()==3)
        {if(jComboBox2.getSelectedIndex()==1){   
        ResultSet rr=st.executeQuery("select Element_name,Atomic_mass,Density,Melting_point,Boiling_point,Electronegativity from elements where (Density='"+de+"');");
       while(rr.next()){
                an=rr.getString("Element_name");
                
        am=rr.getDouble("Atomic_mass");
        de=rr.getDouble("Density");
        mp=rr.getDouble("Melting_point");
        bp=rr.getDouble("Boiling_point");
        en=rr.getDouble("Electronegativity");
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);}
        }
                     
         
        if(jComboBox2.getSelectedIndex()==2){   
            ResultSet rr=st.executeQuery("select * from elements where Density<'"+de+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
            if(jComboBox2.getSelectedIndex()==3){   
            ResultSet rr=st.executeQuery("select * from elements where Density>'"+de+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
        }
        if(jComboBox2.getSelectedIndex()==4){   
            ResultSet rr=st.executeQuery("select * from elements where Density<='"+de+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
        if(jComboBox2.getSelectedIndex()==5){   
            ResultSet rr=st.executeQuery("select * from elements where Density>='"+de+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
       
        
    }}
        mp=Double.parseDouble(jTextField1.getText());
       if(jComboBox1.getSelectedIndex()==4)
        {if(jComboBox2.getSelectedIndex()==1){   
        ResultSet rr=st.executeQuery("select Element_name,Atomic_mass,Density,Melting_point,Boiling_point,Electronegativity from elements where (Melting_point='"+mp+"');");
       while(rr.next()){
                an=rr.getString("Element_name");
                
        am=rr.getDouble("Atomic_mass");
        de=rr.getDouble("Density");
        mp=rr.getDouble("Melting_point");
        bp=rr.getDouble("Boiling_point");
        en=rr.getDouble("Electronegativity");
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);}
        }
                     
         
        if(jComboBox2.getSelectedIndex()==2){   
            ResultSet rr=st.executeQuery("select * from elements where Melting_point<'"+mp+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
            if(jComboBox2.getSelectedIndex()==3){   
            ResultSet rr=st.executeQuery("select * from elements where Melting_point>'"+mp+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
        }
        if(jComboBox2.getSelectedIndex()==4){   
            ResultSet rr=st.executeQuery("select * from elements where Melting_point<='"+mp+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
        if(jComboBox2.getSelectedIndex()==5){   
            ResultSet rr=st.executeQuery("select * from elements where Melting_point>='"+mp+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
       
        
    }} 
       bp=Double.parseDouble(jTextField1.getText());
       if(jComboBox1.getSelectedIndex()==5)
        {if(jComboBox2.getSelectedIndex()==1){   
        ResultSet rr=st.executeQuery("select Element_name,Atomic_mass,Density,Melting_point,Boiling_point,Electronegativity from elements where (Boiling_point='"+bp+"');");
       while(rr.next()){
                an=rr.getString("Element_name");
                
        am=rr.getDouble("Atomic_mass");
        de=rr.getDouble("Density");
        mp=rr.getDouble("Melting_point");
        bp=rr.getDouble("Boiling_point");
        en=rr.getDouble("Electronegativity");
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);}
        }
                     
         
        if(jComboBox2.getSelectedIndex()==2){   
            ResultSet rr=st.executeQuery("select * from elements where Boiling_point<'"+bp+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
            if(jComboBox2.getSelectedIndex()==3){   
            ResultSet rr=st.executeQuery("select * from elements where Boiling_point>'"+bp+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
        }
        if(jComboBox2.getSelectedIndex()==4){   
            ResultSet rr=st.executeQuery("select * from elements where Boiling_point<='"+bp+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
        if(jComboBox2.getSelectedIndex()==5){   
            ResultSet rr=st.executeQuery("select * from elements where Boiling_point>='"+bp+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
       
        
    }}
       en=Double.parseDouble(jTextField1.getText());
       if(jComboBox1.getSelectedIndex()==6)
        {if(jComboBox2.getSelectedIndex()==1){   
        ResultSet rr=st.executeQuery("select Element_name,Atomic_mass,Density,Melting_point,Boiling_point,Electronegativity from elements where (Electronegativity='"+en+"');");
       while(rr.next()){
                an=rr.getString("Element_name");
                
        am=rr.getDouble("Atomic_mass");
        de=rr.getDouble("Density");
        mp=rr.getDouble("Melting_point");
        bp=rr.getDouble("Boiling_point");
        en=rr.getDouble("Electronegativity");
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);}
        }
                     
         
        if(jComboBox2.getSelectedIndex()==2){   
            ResultSet rr=st.executeQuery("select * from elements where Electronegativity<'"+en+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
            if(jComboBox2.getSelectedIndex()==3){   
            ResultSet rr=st.executeQuery("select * from elements where Electronegativity>'"+en+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
        }
        if(jComboBox2.getSelectedIndex()==4){   
            ResultSet rr=st.executeQuery("select * from elements where Electronegativity<='"+en+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }}
        if(jComboBox2.getSelectedIndex()==5){   
            ResultSet rr=st.executeQuery("select * from elements where Electronegativity>='"+en+"'; ");
            while(rr.next()){
                num=rr.getInt(1);
        an=rr.getString(2);
        am=rr.getDouble(3);
        de=rr.getDouble(4);
        mp=rr.getDouble(5);
        bp=rr.getDouble(6);
        en=rr.getDouble(7);
                 
        
                Object rec[]={num,an,am,de,mp,bp,en};
                tt.addRow(rec);
            }
       
        
    }}}
        
        
    catch(Exception e){JOptionPane.showMessageDialog(null,"Your inserted value is not in the range");}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 DefaultTableModel tt=(DefaultTableModel)jTable1.getModel();
    int n=tt.getRowCount();
    {for(int i=0;i<=n;)
        tt.removeRow(i);}
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comparison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comparison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comparison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comparison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comparison().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
